# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0016_auto_20161212_1630'),
        ('uploader', '0002_auto_20161212_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='data_app.Account'),
            preserve_default=False,
        ),
    ]
