# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('heading_date', models.CharField(default='Date', max_length=50)),
                ('heading_description', models.CharField(default='Description', max_length=50)),
                ('heading_in', models.CharField(default='Money In', max_length=50)),
                ('heading_out', models.CharField(default='Money Out', max_length=50)),
                ('heading_balance', models.CharField(default='Balance', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('month_name', models.CharField(max_length=15)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_input', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='data_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('id_description', models.CharField(max_length=250)),
                ('money_in', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('money_out', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_input', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='data_app.Account')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='data_app.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='data_app.Account')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='data_app.Year'),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='data_app.Year'),
        ),
    ]
