# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableentry',
            name='x_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tableentry',
            name='y_value',
            field=models.IntegerField(null=True),
        ),
    ]
