# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_remove_year_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 21, 2, 5, 567029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 21, 2, 5, 567029, tzinfo=utc)),
        ),
    ]
