# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_auto_20161203_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableentry',
            old_name='entry',
            new_name='table',
        ),
    ]
