# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_auto_20161203_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('heading_date', models.CharField(max_length=50)),
                ('heading_description', models.CharField(max_length=50)),
                ('heading_in', models.CharField(max_length=50)),
                ('heading_out', models.CharField(max_length=50)),
                ('heading_balance', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('money_out', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='data_app.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='tableentry',
            name='x_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tableentry',
            name='y_value',
            field=models.FloatField(null=True),
        ),
    ]
