# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_auto_20170204_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
