# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_auto_20161211_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
    ]
