# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_auto_20170204_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='date',
            new_name='month_date',
        ),
    ]
