# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_auto_20161211_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='table',
            new_name='account',
        ),
    ]
