# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_auto_20161211_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='heading_balance',
            field=models.CharField(default='Balance', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='heading_date',
            field=models.CharField(default='Date', max_length=50),
        ),
    ]
