# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0008_remove_month_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_balance',
            field=models.CharField(default=datetime.datetime(2017, 2, 6, 15, 6, 40, 57497, tzinfo=utc), max_length=24),
            preserve_default=False,
        ),
    ]
