# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_auto_20161211_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='net_input',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
