# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0010_transaction_net_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
