# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0012_auto_20161211_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recalculate_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
