# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0013_auto_20161212_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recalculate_balance',
            field=models.BooleanField(default=True),
        ),
    ]
