# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0015_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='account',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
